-- Create the customers table
create table if not exists customers (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  business_name text not null,
  mobile text not null
);

-- Create the tasks table for Kanban board
create table if not exists tasks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  status text default 'todo' check (status in ('todo', 'in_progress', 'done'))
);

-- Create the business_profile table for Context-Aware AI
create table if not exists business_profile (
  id bigint generated by default as identity primary key,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  business_category text,
  location_type text,
  customer_type text,
  revenue_goal numeric
);

-- Insert a default profile row (since we aren't using Auth for this demo, we use ID 1)
insert into business_profile (id, business_category, location_type, customer_type, revenue_goal)
values (1, 'General Store', 'Main Market', 'Local Residents', 100000)
on conflict (id) do nothing;
